name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Connection
        run: |
          echo "BEAGLEBONE_HOST: ${{ secrets.BEAGLEBONE_HOST }}"
          echo "PORT: ${{ secrets.PORT }}"
          # Add more debug commands as needed
          ping -c 5 ${{ secrets.BEAGLEBONE_HOST }}
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.BEAGLEBONE_USERNAME }}@${{ secrets.BEAGLEBONE_HOST }} "echo Connection successful"

      - name: Install SSH and sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: Copy files via SSH
        run: |
          sshpass -p "${{ secrets.BEAGLEBONE_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no -r ./TestDebian/* \
          ${{ secrets.BEAGLEBONE_USERNAME }}@${{ secrets.BEAGLEBONE_HOST }}:${{ secrets.BEAGLEBONE_DESTINATION_PATH }}
