name: Clone Repository to BeagleBone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone_to_beaglebone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get install openssh-client
      
    - name: Copy SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      
    - name: Add GitHub to known hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      
    - name: Clone repository to BeagleBone
      run: |
        ssh -vvv ${{ secrets.BEAGLEBONE_USERNAME }}@${{ secrets.BEAGLEBONE_HOST }} "git clone git@github.com:GayathriDSPy/TestDebian.git ${{ secrets.BEAGLEBONE_DESTINATION_PATH }}"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

