name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Connection
        run: |
          echo "BEAGLEBONE_HOST: ${{ secrets.BEAGLEBONE_HOST }}"
          echo "PORT: ${{ secrets.PORT }}"
          # Add more debug commands as needed

      - name: Deploy to BeagleBone
        run: |
          scp -r -v ./TestDebian/* ${{ secrets.BEAGLEBONE_USERNAME }}@${{ secrets.BEAGLEBONE_HOST }}:${{ secrets.BEAGLEBONE_DESTINATION_PATH }}

      # Add error handling in case of failure
      - name: Check if deployment failed
        if: failure()
        run: echo "Deployment failed. Check the logs for details."
